version: "3.8"

services:
  app:
    container_name: docker-react-c
    image: docker-react-i
    build:
      context: .
    ports:
      - "5000:80"
    restart: unless-stopped
# hinosoft:
#   build:
#     docker:
#       - image: docker-react-i
#         auth:
#           username: anptit2003 # can specify string literal values
#           password: Ann04092003 # or project environment variable reference
